server:
  port: 30305

spring:
  application:
    name: demo-detection
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: aip@local

alinesno.smart:
  detection:
    env: development
    kafkaServers: 192.168.101.18:9092
    user-key: aip@local